services:
  - type: web
    name: monther-portfolio
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        value: "10000"
      - key: HOSTNAME
        value: 0.0.0.0
