import { DAY_CONFIG } from "../dayNight/config";
import {
  HERP_ASPECT,
  ROCK1_ASPECT,
  ROCKH_ASPECT,
} from "../room/floorDecalLayout";
import {
  createTransform,
  createVector3,
  type FloorDecalGroupDebug,
  type FloorDecalItemDebug,
  type RoomDebugState,
} from "./types";

const createFloorDecalGroup = (): FloorDecalGroupDebug => ({
  visible: true,
  position: createVector3(),
  scale: 1,
});

const createFloorDecalItem = (
  id: string,
  label: string,
  textureKey: FloorDecalItemDebug["textureKey"],
  aspect: number,
  position: [number, number, number],
  scale: number,
  renderOrder = 0,
): FloorDecalItemDebug => ({
  id,
  label,
  textureKey,
  aspect,
  visible: true,
  position: createVector3(...position),
  scale,
  renderOrder,
});

/** All default coordinates/colors of the room scene. */
export function createRoomDebugState(): RoomDebugState {
  return {
    scene: {
      dayBackgroundColor: DAY_CONFIG.background,
      dayFogColor: DAY_CONFIG.fog,
      fogNear: 5,
      fogFar: 45,
    },
    environment: {
      studioHdri: {
        visible: true,
        environmentIntensity: DAY_CONFIG.environmentIntensity,
      },
    },
    lights: {
      interiorAmbient: {
        visible: true,
        color: DAY_CONFIG.ambient.color,
        dayIntensity: DAY_CONFIG.ambient.intensity,
      },
    },
    meshes: {
      floor: {
        ...createTransform([0, -3.52, -1.15]),
        visible: true,
      },
      stonePath: {
        ...createTransform([0, -3.01, -4.07], [-Math.PI / 2, 0, 0]),
        visible: true,
      },
      exteriorWall: createTransform(
        [0.0500000000000043, 1.75, -16.15],
        [0, 0, 0],
        [0.84, 0.67, 1],
      ),
      doorRoot: createTransform([0, -0.18, -15.9], [0, 0, 0], [0.6, 0.6, 0.6]),
      doorFrame: createTransform([0, 0, 0.2], [0, 0, 0], [1.01, 1.05, 1]),
      doorPanelPivot: createTransform([-2.555, -0.22, 0]),
      doorPanelSurface: createTransform([0, -0.1, 0]),
      leftLantern: createTransform(
        [-2.85, 0.55, -15.57],
        [0, 0, 0],
        [2.5, 2.5, 2.5],
      ),
      rightLantern: createTransform(
        [2.77, 0.56, -15.57],
        [0, 0, 0],
        [2.5, 2.5, 2.5],
      ),
    },
    interiorDetails: {
      floorDecals: {
        all: {
          ...createFloorDecalGroup(),
          position: createVector3(0, 2.79, 0),
        },
        stones: {
          group: createFloorDecalGroup(),
          items: [
            createFloorDecalItem(
              "stone-01",
              "Stone 01",
              "rock1",
              ROCK1_ASPECT,
              [-5.0, -6.0, -12],
              1.6,
            ),
            createFloorDecalItem(
              "stone-02",
              "Stone + Herp 02",
              "rockHerp",
              ROCKH_ASPECT,
              [5.0, -6.0, -9],
              1.5,
            ),
            createFloorDecalItem(
              "stone-03",
              "Stone 03",
              "rock1",
              ROCK1_ASPECT,
              [-4.0, -6.0, -14],
              0.6,
            ),
            createFloorDecalItem(
              "stone-04",
              "Stone 04",
              "rock1",
              ROCK1_ASPECT,
              [-6.5, -6.0, -9],
              0.5,
            ),
            createFloorDecalItem(
              "stone-05",
              "Stone 05",
              "rock1",
              ROCK1_ASPECT,
              [-4.5, -6.0, -5],
              0.5,
            ),
            createFloorDecalItem(
              "stone-06",
              "Stone 06",
              "rock1",
              ROCK1_ASPECT,
              [-7.0, -6.0, -2],
              0.6,
            ),
            createFloorDecalItem(
              "stone-07",
              "Stone + Herp 07",
              "rockHerp",
              ROCKH_ASPECT,
              [-5.5, -6.0, -15],
              0.6,
            ),
            createFloorDecalItem(
              "stone-08",
              "Stone + Herp 08",
              "rockHerp",
              ROCKH_ASPECT,
              [-4.0, -6.0, -3],
              0.5,
            ),
            createFloorDecalItem(
              "stone-09",
              "Stone + Herp 09",
              "rockHerp",
              ROCKH_ASPECT,
              [-7.5, -6.0, -7],
              0.6,
            ),
            createFloorDecalItem(
              "stone-10",
              "Stone 10",
              "rock1",
              ROCK1_ASPECT,
              [4.0, -6.0, -13],
              0.5,
            ),
            createFloorDecalItem(
              "stone-11",
              "Stone 11",
              "rock1",
              ROCK1_ASPECT,
              [6.5, -6.0, -6],
              0.7,
            ),
            createFloorDecalItem(
              "stone-12",
              "Stone 12",
              "rock1",
              ROCK1_ASPECT,
              [4.5, -6.0, -2],
              0.4,
            ),
            createFloorDecalItem(
              "stone-13",
              "Stone 13",
              "rock1",
              ROCK1_ASPECT,
              [8.0, -6.0, -10],
              0.5,
            ),
            createFloorDecalItem(
              "stone-14",
              "Stone + Herp 14",
              "rockHerp",
              ROCKH_ASPECT,
              [5.5, -6.0, -12],
              0.7,
            ),
            createFloorDecalItem(
              "stone-15",
              "Stone + Herp 15",
              "rockHerp",
              ROCKH_ASPECT,
              [4.0, -6.0, -6],
              0.5,
            ),
            createFloorDecalItem(
              "stone-16",
              "Stone + Herp 16",
              "rockHerp",
              ROCKH_ASPECT,
              [7.0, -6.0, -3],
              0.6,
            ),
          ],
        },
        herps: {
          group: createFloorDecalGroup(),
          items: [
            createFloorDecalItem(
              "herp-01",
              "Herp 01",
              "herp",
              HERP_ASPECT,
              [-5.5, -6.0, -7],
              1.8,
            ),
            createFloorDecalItem(
              "herp-02",
              "Herp 02",
              "herp",
              HERP_ASPECT,
              [5.5, -6.0, -4],
              1.6,
            ),
            createFloorDecalItem(
              "herp-03",
              "Herp 03",
              "herp",
              HERP_ASPECT,
              [-4.5, -6.0, -11],
              0.8,
            ),
            createFloorDecalItem(
              "herp-04",
              "Herp 04",
              "herp",
              HERP_ASPECT,
              [-6.0, -6.0, -2],
              0.5,
            ),
            createFloorDecalItem(
              "herp-05",
              "Herp 05",
              "herp",
              HERP_ASPECT,
              [-8.0, -6.0, -12],
              0.6,
            ),
            createFloorDecalItem(
              "herp-06",
              "Herp 06",
              "herp",
              HERP_ASPECT,
              [4.5, -6.0, -8],
              0.6,
            ),
            createFloorDecalItem(
              "herp-07",
              "Herp 07",
              "herp",
              HERP_ASPECT,
              [7.0, -6.0, -5],
              0.7,
            ),
            createFloorDecalItem(
              "herp-08",
              "Herp 08",
              "herp",
              HERP_ASPECT,
              [9.0, -6.0, -13],
              0.5,
            ),
          ],
        },
      },
    },
    materials: {
      floor: {
        color: "#ffffff",
        roughness: 1,
        metalness: 0,
        bumpScale: 0.02,
        wireframe: false,
      },
      stonePath: {
        color: "#ffffff",
        roughness: 0.9,
        metalness: 0,
        wireframe: false,
      },
      exteriorWall: {
        color: "#ffffff",
        roughness: 0.9,
        metalness: 0,
        wireframe: false,
      },
      doorFrame: {
        color: "#ffffff",
        roughness: 1,
        metalness: 0,
        wireframe: false,
      },
      doorPanel: {
        color: "#ffffff",
        roughness: 1,
        metalness: 0,
        wireframe: false,
      },
    },
  };
}
