"use client";

import React, { useEffect } from "react";
import { ScrollControls } from "@react-three/drei";
import FlightPath from "./FlightPath";

export default function PaperPlaneScene() {
  // Hide scrollbars for the ScrollControls overlay dynamically
  useEffect(() => {
    const style = document.createElement("style");
    style.id = "hide-scrollbar-style";
    // Target all scrollbars, including the div generated by ScrollControls
    style.innerHTML = `
      *::-webkit-scrollbar { 
        display: none !important; 
        width: 0 !important; 
        background: transparent !important; 
      }
      * {
        scrollbar-width: none !important;
        -ms-overflow-style: none !important;
      }
    `;
    document.head.appendChild(style);

    return () => {
      const styleEl = document.getElementById("hide-scrollbar-style");
      if (styleEl) styleEl.remove();
    };
  }, []);

  return (
    <>
      {/* 
        ScrollControls automatically manages an invisible HTML scroll container 
        over the canvas, allowing us to scrub through animations using useScroll()!
      */}
      <ScrollControls pages={10} damping={0.25}>
        <FlightPath />
      </ScrollControls>
    </>
  );
}
